apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-gateway
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: uksouth
            server: https://cluster1-endpoint
            values:
              region: uksouth
          - name: ukwest
            server: https://cluster2-endpoint
            values:
              region: ukwest
  template:
    metadata:
      name: 'istio-gateway-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: gateway
        targetRevision: 1.20.0
        helm:
          values: |
            global:
              istioNamespace: istio-system
            service:
              # Use LoadBalancer for Azure Front Door
              type: LoadBalancer
              ports:
                - name: http2
                  port: 80
                  targetPort: 80
              annotations:
                service.beta.kubernetes.io/azure-load-balancer-internal: "false"
            autoscaling:
              enabled: true
              minReplicas: 2
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
      destination:
        server: '{{server}}'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true 