apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-gateway
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: uksouth
            url: https://aks-uksouth-dns
          - cluster: ukwest
            url: https://aks-ukwest-dns
  template:
    metadata:
      name: 'istio-gateway-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/kofiray/istio-multicluster-argocd.git
        targetRevision: HEAD
        path: manifests/gateway
      destination:
        server: '{{url}}'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true 