apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-gateway
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: uksouth
            server: https://kubernetes.default.svc
          - cluster: ukwest
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: 'istio-gateway-{{cluster}}'
    spec:
      project: istio-system
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: gateway
        targetRevision: 1.20.0
        helm:
          values: |
            global:
              istioNamespace: istio-system
            service:
              type: LoadBalancer
              ports:
                - name: http2
                  port: 80
                  targetPort: 8080
                - name: https
                  port: 443
                  targetPort: 8443
              annotations:
                service.beta.kubernetes.io/azure-load-balancer-internal: "false"
            replicaCount: 3
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                cpu: 2000m
                memory: 2Gi
            nodeSelector:
              purpose: istio-gateway
            tolerations:
              - key: purpose
                operator: Equal
                value: istio-gateway
                effect: NoSchedule
      destination:
        server: '{{server}}'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true 