apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-base
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: uksouth
            server: https://kubernetes.default.svc
            values:
              region: uksouth
          - name: ukwest
            server: https://kubernetes.default.svc
            values:
              region: ukwest
  template:
    metadata:
      name: 'istio-base-{{name}}'
    spec:
      project: istio-system
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: base
        targetRevision: 1.20.0
        helm:
          values: |
            global:
              istioNamespace: istio-system
      destination:
        server: '{{server}}'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true 